# -*- coding: utf-8 -*-
"""Metodo Format.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c_fmP5ee5dObjKBTBdywpH0Hh6k5_bXW

### Forma que fizemos na última aula (concatenando textos)
"""

faturamento = 2000
custo = 500
lucro = faturamento - custo

print('O faturamento da loja foi ' + str(faturamento) + '.O custo da loja foi ' + str(custo) + '.Assim, o lucro da loja foi de ' + str(lucro))

"""### Método format"""

