# -*- coding: utf-8 -*-
"""Listas 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKfvCuPtowTxtRHlAP1mVNJWo8YcNG5T

# Listas em Python

## Estrutura:

lista = [valor, valor, valor, valor, ...]

- Lista é um dos objetos mais importantes de Python, por isso vamos trabalhar bastante neles
- Quando importamos uma base de dados para o Python, normalmente ele é lido como uma "lista" ou como alguma "variação de lista"
- Listas em Python foram feitas para serem homogêneas, apesar de aceitarem valores heterogêneos
- Exemplos de Lista:

Listas de Produtos de uma Loja:
"""

produtos = ['tv', 'celular', 'mouse', 'teclado', 'tablet']

"""Lista de Unidades Vendidas de cada Produto da Loja"""

vendas = [1000, 1500, 350, 270, 900]